# Generated by Django 3.0.4 on 2020-03-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UI_element', models.CharField(max_length=200)),
            ],
        ),
    ]
