# Generated by Django 3.0.4 on 2020-03-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Content',
        ),
    ]
