# Generated by Django 3.0.4 on 2020-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200311_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='UI_element',
        ),
        migrations.AddField(
            model_name='content',
            name='css',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='subtree',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
    ]
